CS4540PS2/Models/DB/LearningOutcomes.cs
using System;
using System.Collections.Generic;

namespace CS4540PS2.Models
{
    public partial class LearningOutcomes
    {
        public LearningOutcomes()
        {
            EvaluationMetrics = new HashSet<EvaluationMetrics>();
            LONotes = new HashSet<LONotes>();
        }

        public int Loid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CourseInstanceId { get; set; }

        public virtual CourseInstance CourseInstance { get; set; }
        public virtual ICollection<EvaluationMetrics> EvaluationMetrics { get; set; }
        public virtual ICollection<LONotes> LONotes { get; set; }
    }
}

CS4540PS2/Controllers/LearningOutcomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CS4540PS2.Models;
using Microsoft.AspNetCore.Authorization;

/// <summary>
/// Author: Valerie German
/// Date: 10 Sept 2019
/// Course: CS 4540, University of Utah
/// Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
/// I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
/// File Contents: This file contains controller for learning outcome webpages. Admins may create/edit/delete learning outcomes. These actions are only available to admins.
/// </summary>
namespace CS4540PS2.Controllers {
    [Authorize(Roles = "Admin")]
    public class LearningOutcomesController : Controller {
        private readonly LOTDBContext _context;
        public LearningOutcomesController(LOTDBContext context) {
            _context = context;
        }

        /// <summary>
        /// Returns index page listing all learning outcomes.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber, int resultsPerPage = 5) {
            ViewData["PageNumber"] = pageNumber;
            ViewData["ResultsPerPage"] = resultsPerPage;
            // Set up the possible ordering schemes of the table.
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CourseNumSortParam"] = sortOrder == "courseNum_asc" ? "courseNum_desc" : "courseNum_asc";
            
            // If there is a search string, filter by that, otherwise use the default
            if (searchString != null) {
                pageNumber = 1;
            }
            else {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            // get learning outcomes
            var learningOutcomes = _context.LearningOutcomes
                .Include(l => l.CourseInstance)
                .OrderBy(l => l.Name)
                .AsNoTracking();    
            
            if (learningOutcomes.Count() == 0)
                return View();

            // allow the user to search the learning outcomes
            learningOutcomes = FilterBySearch(searchString, learningOutcomes);

            // reorder the results based on the selected filter
            learningOutcomes = OrderBySelection(sortOrder, learningOutcomes);

            //if (learningOutcomes.Count() == 0)
            //    return View();

            return View(await PaginatedList<LearningOutcomes>.CreateAsync(learningOutcomes.AsNoTracking(), pageNumber ?? 1, resultsPerPage));
        }

        /// <summary>
        /// Filters the learning outcomes returned by the database by a user supplied search string.
        /// </summary>
        private IQueryable<LearningOutcomes> FilterBySearch(string searchString, IQueryable<LearningOutcomes> learningOutcomes) {
            // allow the user to search
            if (!string.IsNullOrEmpty(searchString)) {
                string[] searchWords = searchString.Split(' ');
                foreach (string s in searchWords) {
                    if (!string.IsNullOrEmpty(s)) {                       
                            learningOutcomes = learningOutcomes.Where(l => l.Name.Contains(s)
                            || l.Description.Contains(s)
                            || l.CourseInstance.Number.ToString().Equals(s));                        
                    }
                }
            }
            return learningOutcomes;
        }

        /// <summary>
        /// Reorders the learning outcomees in the view based on user selection
        /// </summary>
        private IQueryable<LearningOutcomes> OrderBySelection(string sortOrder, IQueryable<LearningOutcomes> learningOutcomes)
        {
            // reorder the results based on the selected filter           
            switch (sortOrder) {
                case "name_desc":
                    learningOutcomes = learningOutcomes.OrderByDescending(l => l.Name);
                    break;
                case "courseNum_asc":
                    learningOutcomes = learningOutcomes.OrderBy(l => l.CourseInstance.Number);
                    break;
                case "courseNum_desc":
                    learningOutcomes = learningOutcomes.OrderByDescending(l => l.CourseInstance.Number);
                    break;               
                default:
                    learningOutcomes = learningOutcomes.OrderBy(l => l.Name);
                    break;
            }
            return learningOutcomes;
        }

        /// <summary>
        /// Redirects to the course department view page with course with given CourseInstanceId
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> RedirectToCourse(int? id) {
            if (id == null)
                return View("Error", new ErrorViewModel() {
                    ErrorMessage = "Insufficient information to locate course."
                });
            using (_context) {
                CourseInstance getid = (from courses in _context.CourseInstance
                                        where courses.CourseInstanceId == id
                                        select courses).FirstOrDefault<CourseInstance>();
                if (getid == null)
                    return View("Error", new ErrorViewModel() {
                        ErrorMessage = "Insufficient information to locate course."
                    });
                return await Course(getid.Department, getid.Number, getid.Semester, getid.Year);
            }
        }

#pragma warning disable CS1998  // Async method lacks 'await' operators and will run synchronously
        /// <summary>
        /// Course department view page.
        /// </summary>
        /// <param name="Dept"></param>
        /// <param name="Num"></param>
        /// <param name="Sem"></param>
        /// <param name="Year"></param>
        /// <returns></returns>
        public async Task<IActionResult> Course(string Dept, int? Num, string Sem, int? Year)
        {
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
            if (Dept.Equals(null) || Num == null || Sem.Equals(null) || Year == null)
                return View("Error", new ErrorViewModel() {
                    ErrorMessage = "Insufficient information to locate course."
                });
            CourseInstance course = _context.CourseInstance.Where(c => c.Department == Dept && c.Number == Num
                && c.Semester == Sem && c.Year == Year)
                .Include(c => c.CourseNotes)
                .Include(c => c.LearningOutcomes)
                .ThenInclude(lo => lo.EvaluationMetrics)
                .ThenInclude(em => em.SampleFiles)
                .Include(c => c.LearningOutcomes)
                .ThenInclude(lo => lo.LONotes)
                .FirstOrDefault();
            if(course == null) {
                return Forbid();
            }
            return View("Course", course);
        }


        /// <summary>
        /// GET Returns information about a learning outcome
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var learningOutcomes = await _context.LearningOutcomes
                .Include(l => l.CourseInstance)
                .FirstOrDefaultAsync(m => m.Loid == id);
            if (learningOutcomes == null) {
                return NotFound();
            }

            return View(learningOutcomes);
        }

        /// <summary>
        /// GET Returns page for creating a learning outcome.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create() {
            ViewData["CourseInstances"] = _context.CourseInstance.ToList<CourseInstance>();
            return View();
        }

        /// <summary>
        /// POST Creates a new learning outcome.
        /// </summary>
        /// <param name="learningOutcomes"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Loid,Name,Description,CourseInstanceId")] LearningOutcomes learningOutcomes) {
            if (ModelState.IsValid) {
                _context.Add(learningOutcomes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseInstanceId"] = new SelectList(_context.CourseInstance, "CourseInstanceId", "Department", learningOutcomes.CourseInstanceId);
            return View(learningOutcomes);
        }

        /// <summary>
        /// GET Returns page for editing a learning outcome
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var learningOutcomes = await _context.LearningOutcomes.FindAsync(id);
            if (learningOutcomes == null) {
                return NotFound();
            }
            ViewData["CourseInstanceId"] = new SelectList(_context.CourseInstance, "CourseInstanceId", "Department", learningOutcomes.CourseInstanceId);
            return View(learningOutcomes);
        }

        /// <summary>

CS4540PS2/Views/LearningOutcomes/Course.cshtml
@model CS4540PS2.Models.CourseInstance
@*
    Author: Valerie German
    Date: 10 Sept 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
    I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: Department view of a course - ability to update learning outcomes.
*@
@{
    @using Newtonsoft.Json.Linq;
    @using CS4540PS2.Controllers;
    ViewData["Title"] = Model.Number;
}

    <div id="ContentDiv">
        <h1>@Model.Department @Model.Number @Model.Name</h1>
        <h4>@Model.Description<!--Professor name--></h4>
        <div align="right">
            <a asp-controller="LearningOutcomes" asp-action="Index">All Learning Outcomes</a>
        </div>
        <hr />
        <h2>Learning Outcomes</h2>
        <h5 align="right">
            Add Learning Outcome
            <button type="button" class="btn btn-rounded btn-dark btn-sm" data-toggle="modal" data-target="#loModal">
                <i>+</i>
            </button>
        </h5>
        @if (Model.LearningOutcomes.Count == 0) {
            <p><b>This course has no assigned learning outcomes.</b></p>
        }
        @foreach (LearningOutcomes lo in Model.LearningOutcomes) {
            <!--Collapses separated in divs-->
            <!--Collapse with information about a learning outcome-->
            <!--This and following collapses created with help from https://getbootstrap.com/docs/4.0/components/collapse/-->
            <button class="btn sectionButton text-left lot-expando-btn" type="button" data-toggle="collapse"
                    data-target="#collapseContent@{<text>@lo.Loid</text>}" aria-expanded="false"
                    aria-controls="collapseContent@{<text>@lo.Loid</text>}">
                <b>@lo.Name</b>
            </button>
            <div class="collapse show" id="collapseContent@{<text>@lo.Loid</text>}">
                <!--Cards reference https://getbootstrap.com/docs/4.1/components/card/ (this is true of all following cards).-->
                <div class="card card-body">
                    <div class="card">
                        <div class="card-body">
                            @lo.Description
                        </div>
                    </div>
                    <br />
                    <div align="right">
                        <a class="btn btn-danger btn-sm" asp-controller="LearningOutcomes" asp-action="Delete" asp-route-id="@lo.Loid">Delete</a>
                        <a class="btn btn-primary btn-sm" asp-controller="LearningOutcomes" asp-action="Edit" asp-route-id="@lo.Loid">Modify</a>
                    </div>
                </div>
            </div><!--End Collapse Div-->
        }
        <br />


        <div class="modal fade" id="loModal" tabindex="-1" role="dialog" aria-labelledby="learningOutcomeModal" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="learningOutcomeModal">Add Learning Outcome</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <!--Referenced https://getbootstrap.com/docs/4.1/components/forms/ for form layout-->
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label class="control-label">Name</label>
                                <input name="Name" class="form-control" placeholder="Insert Name" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Description</label>
                                <input name="Description" class="form-control" placeholder="Insert Description" />
                            </div>
                            <div class="form-group">
                                <input hidden="hidden" name="CourseInstanceId" class="form-control" value="@Model.CourseInstanceId" />
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <br />
    </div>

CS4540PS2/Views/LearningOutcomes/Create.cshtml
@model CS4540PS2.Models.LearningOutcomes
@*
    Author: Valerie German
    Date: 10 Sept 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
    I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: Webpage for creating learning outcomes.
*@
@{
    ViewData["Title"] = "Create";
    List<CourseInstance> instances = (List<CourseInstance>) ViewData["CourseInstances"];
}

<h1>Create</h1>

<h4>LearningOutcomes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseInstanceId" class="control-label">Course</label>
                <select asp-for="CourseInstanceId" class="form-control">
                    <option disabled selected>Select a course</option>
                @foreach(CourseInstance inst in instances) {
                    <option name="CourseInstanceId" value="@inst.CourseInstanceId">@inst.Department @inst.Number @inst.Name (@inst.Semester @inst.Year)</option>
                }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<br />
<div>
    <a asp-action="Index"><button class="btn btn-sm btn-light">Back To All Learning Outcomes</button></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CS4540PS2/Views/LearningOutcomes/Delete.cshtml
@model CS4540PS2.Models.LearningOutcomes
@*
    Author: Valerie German
    Date: 10 Sept 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
    I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: Webpage for deleting learning outcomes.
*@
@{
    ViewData["Title"] = "Delete";
    string course = Model.CourseInstance.Department + Model.CourseInstance.Number + " " + Model.CourseInstance.Name + 
        " (" + Model.CourseInstance.Semester + " " + Model.CourseInstance.Year + ")";
}
<h3>Are you sure you want to delete this learning outcome?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CourseInstance)
        </dt>
        <dd class="col-sm-10">
            <p>@course</p>
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Loid" />
        <input type="submit" value="Delete" class="btn btn-danger" /><br /><br />
        <a asp-action="Course" asp-route-Dept="@Model.CourseInstance.Department" asp-route-Num="@Model.CourseInstance.Number"
           asp-route-Sem="@Model.CourseInstance.Semester" asp-route-Year="@Model.CourseInstance.Year"><button class="btn btn-sm btn-dark">Back to Course</button></a> | 
        <a asp-action="Index"><button class="btn btn-sm btn-light">Back To All Learning Outcomes</button></a>
</form>
</div>

CS4540PS2/Views/LearningOutcomes/Index.cshtml
@*
    Author: Valerie German, Cody Winters
    Date: 10 Sept 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540, Valerie German and Cody Winters - This work may not be copied for use in Academic Coursework.
    We, Valerie German and Cody Winters, certify that we wrote this code from scratch and did not copy it in part or 
    whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: Webpage for viewing all existing learning outcomes.
*@

@{
    ViewData["Title"] = "Learning Outcomes";
}

<div align="left" class="halfWidth">
    <h1>Learning Outcomes</h1>
</div>



<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
        </p>
    </div>
</form>

<div name="orderByBar" id="orderByMenu" class="dropdown">
    <button name="orderByDropDownMenuButton" id="orderByDropDownMenuButton" class="btn btn-default dropdown-toggle"
            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Order By
    </button>
    <div name="orderByDropDownMenuItems" id="orderByDropDownMenuItems" class="dropdown-menu" aria-labelledby="orderByDropDownMenuButton">
        <a class="dropdown-item" asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Title</a>
        <a class="dropdown-item" asp-action="Index" asp-route-sortOrder="@ViewData["CourseNumSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Course Number</a>
    </div>
</div>




<hr />

@if (Model != null)
{
    foreach (LearningOutcomes lo in Model)
    {
        <div class="card shadowBox">
            <div class="card-body">
                <p>@lo.Name</p>
                <p>
                    @lo.CourseInstance.Department @lo.CourseInstance.Number -
                    <a asp-action="Course" asp-route-Dept="@lo.CourseInstance.Department" asp-route-Num="@lo.CourseInstance.Number"
                       asp-route-Sem="@lo.CourseInstance.Semester" asp-route-Year="@lo.CourseInstance.Year">
                        <b>@lo.CourseInstance.Name</b>
                    </a>
                </p>
                <p>@lo.Description</p>
            </div>

            <div align="right">
                <a class="btn btn-danger" asp-controller="LearningOutcomes" asp-action="Delete" asp-route-id="@lo.Loid">Delete</a>
                <a class="btn btn-primary" asp-controller="LearningOutcomes" asp-action="Edit" asp-route-id="@lo.Loid">Modify</a>
            </div>
        </div>
        <br />
    }

    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    
    <!-- Page navigation within the index. -->
    <div>
        <!-- The folowing links allow the user to navigate between pages of items in the index view-->
        <nav id="LoIndexPageNavigation" aria-label="Page navigation">
            <ul id="LoIndexPageNavigationList" class="pagination" style="float:left">
                <li id="LoIndexFirstPageButtonListItem" class="page-item @prevDisabled">
                    <a id="LoIndexFirstPageButton" class="page-link" aria-label="First"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="1"
                       asp-route-resultsPerPage="@ViewData["ResultsPerPage"]"
                       asp-route-currentFilter="@ViewData[" CurrentFilter"]">
                        <span aria-hidden="true">&lt;&lt;</span>
                        <span class="sr-only">First Page</span>
                    </a>
                </li>
                <li id="LoIndexPreviousPageButtonListItem" class="page-item @prevDisabled">
                    <a id="LoIndexPreviousPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-resultsPerPage="@ViewData["ResultsPerPage"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        <span aria-hidden="true">&lt;</span>
                        <span class="sr-only">Previous Page</span>
                    </a>
                </li>
                <li id="LoIndexCurrentPageListItem" class="page-item disabled">
                    <a id="LoIndexCurrentPage" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber=pageNumTextBox.text
                       asp-route-resultsPerPage="@ViewData["ResultsPerPage"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        <span aria-hidden="true"><b>@Model.PageIndex </b></span>
                        <span class="sr-only">Current Page: @Model.PageIndex</span>
                    </a>
                </li>
                <li id="LoIndexNextPageButtonListItem" class="page-item @nextDisabled">
                    <a id="LoIndexNextPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-resultsPerPage="@ViewData["ResultsPerPage"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        <span aria-hidden="true">></span>
                        <span class="sr-only">Next Page</span>
                    </a>
                </li>
                <li id="LoIndexLastPageButtonListItem" class="page-item @nextDisabled">
                    <a id="LoIndexLastPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.TotalPages)"
                       asp-route-resultsPerPage="@ViewData["ResultsPerPage"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        <span aria-hidden="true">>></span>
                        <span class="sr-only">Last Page</span>
                    </a>
                </li>
            </ul>

            <!-- The folowing links allow the user to set the number of learning outcomes to view per page-->
            <ul id="LoIndexPageNavigationList" class="pagination" style="float:right">
                <li id="LoIndexLastPageButtonListItem" class="page-item disabled">
                    <a id="LoIndexLastPageButton" class="page-link">
                        <span aria-hidden="true">Elements per page:</span>
                        <span class="sr-only">Last Page</span>
                    </a>
                </li>
                <li id="LoIndexFirstPageButtonListItem" class="page-item">
                    <a id="LoIndexFirstPageButton" class="page-link" aria-label="First"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-resultsPerPage=2>
                        <span aria-hidden="true">2</span>
                        <span class="sr-only">First Page</span>
                    </a>
                </li>
                <li id="LoIndexPreviousPageButtonListItem" class="page-item">
                    <a id="LoIndexPreviousPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-resultsPerPage=5>
                        <span aria-hidden="true">5</span>
                        <span class="sr-only">Previous Page</span>
                    </a>
                </li>
                <li id="LoIndexCurrentPageListItem" class="page-item">
                    <a id="LoIndexCurrentPage" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-resultsPerPage=10>
                        <span aria-hidden="true">10</span>
                        <span class="sr-only">Current Page: @Model.PageIndex</span>
                    </a>
                </li>
                <li id="LoIndexNextPageButtonListItem" class="page-item">
                    <a id="LoIndexNextPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-resultsPerPage=25>
                        <span aria-hidden="true">25</span>
                        <span class="sr-only">Next Page</span>
                    </a>
                </li>
                <li id="LoIndexLastPageButtonListItem" class="page-item">
                    <a id="LoIndexLastPageButton" class="page-link"
                       asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-resultsPerPage=2000000000>
                        <span aria-hidden="true">All</span>
                        <span class="sr-only">Last Page</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div style="clear:left"></div>
    </div>
}
else
{
    <h2> Your search returned no results.</h2>
}

@{

}