CS4540PS2/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS4540PS2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

/// <summary>
/// Author: Valerie German
/// Date: 6 Dec 2019
/// Course: CS 4540, University of Utah
/// Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
/// I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
/// File Contents: This file contains controller for department webpages. Chair pages for viewing departments and courses. Chairs may also manage course notifications.
/// </summary>
namespace CS4540PS2.Controllers {
    [Authorize(Roles = "Chair")]
    public class DepartmentController : Controller {
        private readonly LOTDBContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        public DepartmentController(LOTDBContext context, RoleManager<IdentityRole> role) {
            _context = context;
            _roleManager = role;
        }

        /// <summary>
        /// Returns a list of departments.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index() {
            return View("Index", _context.Departments.OrderBy(d => d.Code));
        }

        /// <summary>
        /// Returns a course overview (chair view) containing information about a course, its learning
        /// outcomes, evaluation metrics and sample files.
        /// </summary>
        /// <param name="CourseId"></param>
        /// <returns></returns>
        public async Task<IActionResult> Course(int CourseId) {
            CourseInstance course = await _context.CourseInstance
                .Include(lo => lo.LearningOutcomes)
                .ThenInclude(em => em.EvaluationMetrics)
                .ThenInclude(sa => sa.SampleFiles)
                .Include(lo => lo.LearningOutcomes)
                .ThenInclude(no => no.LONotes)
                .Include(c => c.Status)
                .Include(c => c.Instructors)
                .ThenInclude(i => i.User)
                .Where(c => c.CourseInstanceId == CourseId).FirstOrDefaultAsync();
            if (course == null) {
                return NotFound();
            }
            return View("Course", course);
        }

        /// <summary>
        /// Update the course's due date. Returns success boolean in JsonResult.
        /// </summary>
        /// <param name="courseId"></param>
        /// <param name="newDueDate"></param>
        /// <returns></returns>
        public async Task<IActionResult> UpdateCourseDueDate(int? courseId, DateTime newDueDate) {
            if(courseId == null || newDueDate == null) {
                return new JsonResult(new { success = false });
            }
            CourseInstance course = await _context.CourseInstance.Where(c => c.CourseInstanceId == courseId).FirstOrDefaultAsync();
            if (course == null) new JsonResult(new { success = false });
            course.DueDate = newDueDate;
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Sets the course status to approved for the given course.
        /// </summary>
        /// <param name="courseId"></param>
        /// <returns></returns>
        public async Task<IActionResult> ApproveCourse(int? courseId) {
            if (courseId == null) {
                return new JsonResult(new { success = false });
            }
            CourseInstance course = await _context.CourseInstance.Include(c => c.Status).Include(c => c.Instructors).ThenInclude(i => i.User)
                .Where(c => c.CourseInstanceId == courseId).FirstOrDefaultAsync();
            CourseStatus complete = _context.CourseStatus.Where(s => s.Status == CourseStatusNames.Complete).FirstOrDefault();
            if(complete == null) return new JsonResult(new { success = false });
            course.Status = complete;
            //Notify Instructors
            foreach (Instructors inst in course.Instructors) {
                Notifications notify = new Notifications() {
                    CourseInstance = course,
                    User = inst.User,
                    Text = "This course was approved.",
                    DateNotified = DateTime.Now,
                    Read = false
                };
                _context.Notifications.Add(notify);
            }
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Sets the course status to in-review for the given course.
        /// </summary>
        /// <param name="courseId"></param>
        /// <returns></returns>
        public async Task<IActionResult> SetReviewCourse(int? courseId, string message) {
            if (courseId == null) {
                return new JsonResult(new { success = false });
            }
            CourseInstance course = await _context.CourseInstance.Include(c => c.Status)
                .Include(c => c.Instructors).ThenInclude(i => i.User)
                .Where(c => c.CourseInstanceId == courseId).FirstOrDefaultAsync();
            CourseStatus inRev = _context.CourseStatus.Where(s => s.Status == CourseStatusNames.InReview).FirstOrDefault();
            if (inRev == null) return new JsonResult(new { success = false });
            course.Status = inRev;
            //Notify Instructors
            foreach(Instructors inst in course.Instructors) {
                Notifications notify = new Notifications() {
                    CourseInstance = course,
                    User = inst.User,
                    Text = "The course status was set to in-review. Chair message: " + message,
                    DateNotified = DateTime.Now,
                    Read = false
                };
                _context.Notifications.Add(notify);
            }
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Sets the course status to approved for the given course.
        /// </summary>
        /// <param name="courseId"></param>
        /// <returns></returns>
        public async Task<IActionResult> ArchiveCourse(int? courseId) {
            if (courseId == null) {
                return new JsonResult(new { success = false });
            }
            CourseInstance course = await _context.CourseInstance.Include(c => c.Status).Include(c => c.Instructors).ThenInclude(i => i.User)
                .Where(c => c.CourseInstanceId == courseId).FirstOrDefaultAsync();
            CourseStatus archive = _context.CourseStatus.Where(s => s.Status == CourseStatusNames.Archived).FirstOrDefault();
            if (archive == null) return new JsonResult(new { success = false });
            course.Status = archive;
            //Notify Instructors
            foreach (Instructors inst in course.Instructors) {
                Notifications notify = new Notifications() {
                    CourseInstance = course,
                    User = inst.User,
                    Text = "This course was archived.",
                    DateNotified = DateTime.Now,
                    Read = false
                };
                _context.Notifications.Add(notify);
            }
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Updates the identified learning outcome's note along with the last modified date and last user
        /// modifying date.
        /// </summary>
        /// <param name="LearningOutcomeId"></param>
        /// <param name="NewNote"></param>
        /// <returns></returns>
        public JsonResult ChangeNote(int LearningOutcomeId, string NewNote) {
            LearningOutcomes lo = _context.LearningOutcomes.Include(l => l.LONotes)
                .Where(l => l.Loid == LearningOutcomeId).FirstOrDefault();
            if (lo == null) return Json(new { success = false });
            if (lo.LONotes.Count == 0) {
                lo.LONotes.Add(new LONotes());
            }
            lo.LONotes.First().Note = NewNote;
            lo.LONotes.First().NoteModified = DateTime.Now;
            lo.LONotes.First().NoteUserModified = User.Identity.Name;
            _context.SaveChanges();
            return Json(new { success = true, noteContent = NewNote, modified = lo.LONotes.First().NoteModified, user = User.Identity.Name });
        }

        /// <summary>
        /// Retries the file associated with the sample file. Returns NotFound if the file is null, the user has invalid permissions
        /// or the record doesn't exist.
        /// </summary>
        /// <param name="sfId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetSampleFile(int? sfId) {
            SampleFiles sfObj = _context.SampleFiles.Where(s => s.Sid == sfId).FirstOrDefault();
            if (sfObj == null || sfObj.FileContent == null || sfObj.ContentType == null || sfObj.FileName == null) {
                return NotFound();
            }
            return File(sfObj.FileContent, sfObj.ContentType, sfObj.FileName);
        }

        /// <summary>
        /// Returns a department page, listing classes with the given department
        /// code.
        /// </summary>
        /// <param name="DeptCode"></param>
        /// <returns></returns>
        public async Task<IActionResult> Department(string DeptCode) {
            if (DeptCode == null) { DeptCode = "CS"; } //Temp for viewing
            Departments deptDB = _context.Departments.Where(d => d.Code == DeptCode)

CS4540PS2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CS4540PS2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

/// <summary>
/// Author: Valerie German
/// Date: 6 Dec 2019
/// Course: CS 4540, University of Utah
/// Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
/// I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
/// File Contents: This file contains controller for home webpages.
/// </summary>
namespace CS4540PS2.Controllers {
    public class HomeController : Controller {
        private readonly LOTDBContext _context;
        /// <summary>
        /// Creates home controller with given database context.
        /// </summary>
        /// <param name="context"></param>
        public HomeController(LOTDBContext context) {
            _context = context;
        }
        /// <summary>
        /// Default home page.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index() {
            return View();
        }

        /// <summary>
        /// Project overview page
        /// </summary>
        /// <returns></returns>
        public IActionResult Overview() {
            return View();
        }

        /// <summary>
        /// Display the user's notifications
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult Notifications() {
            UserLocator userLoc = _context.UserLocator.Where(u => u.UserLoginEmail == User.Identity.Name)
                .Include(u => u.Notifications)
                .ThenInclude(n => n.CourseInstance)
                .FirstOrDefault();
            if (userLoc == null) return NotFound();
            return View(userLoc);
        }

        /// <summary>
        /// Marks the given notification as read if the notification belongs to the current user.
        /// </summary>
        /// <param name="notificationId"></param>
        /// <returns></returns>
        [Authorize]
        public IActionResult ReadNotification(int? notificationId) {
            if (notificationId == null) return new JsonResult(new { success = false });
            Notifications notify = _context.Notifications.Include(n => n.User)
                .Where(n => n.NotificationId == notificationId && n.User.UserLoginEmail == User.Identity.Name).FirstOrDefault();
            if (notify == null) return new JsonResult(new { success = false });
            notify.Read = true;
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Removes the given notification entry.
        /// </summary>
        /// <param name="notificationId"></param>
        /// <returns></returns>
        [Authorize]
        public IActionResult DeleteNotification(int? notificationId) {
            if (notificationId == null) return new JsonResult(new { success = false });
            Notifications notify = _context.Notifications.Include(n => n.User)
                .Where(n => n.NotificationId == notificationId && n.User.UserLoginEmail == User.Identity.Name).FirstOrDefault();
            if (notify == null) return new JsonResult(new { success = false });
            _context.Notifications.Remove(notify);
            _context.SaveChanges();
            return new JsonResult(new { success = true });
        }

        /// <summary>
        /// Error
        /// </summary>
        /// <returns></returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

CS4540PS2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS4540PS2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

/// <summary>
/// Author: Valerie German
/// Date: 6 Dec 2019
/// Course: CS 4540, University of Utah
/// Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
/// I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
/// File Contents: This file contains controller for displaying and modifying users and roles.
/// </summary>
namespace CS4540PS2.Controllers {
    [Authorize(Roles="Admin")]
    public class UserController : Controller {
        private readonly LOTDBContext _context;
        private readonly UserContext _userContext;
        private UserManager<IdentityUser> _userManager;
        /// <summary>
        /// Construct a course controller with a database context.
        /// </summary>
        /// <param name="context"></param>
        public UserController(LOTDBContext context, UserContext userContext, UserManager<IdentityUser> userManager) {
            _context = context;
            _userContext = userContext;
            _userManager = userManager;
        }
        /// <summary>
        /// View containing all users, where user roles can be modified.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index() {
            return View(_context.UserLocator);
        }

        /// <summary>
        /// Changes the given user's status of the given role. If the user has that role, the user is removed from that
        /// role, if the user is not in that role the user is given that role.
        /// If the user is the last administrator, a warning is returned.
        /// </summary>
        /// <param name="username"></param>
        /// <param name="role"></param>
        /// <returns></returns>
        public JsonResult ChangeRole(string username, string role) {
            IdentityUser user = _userContext.Users.Where(u => u.UserName == username).FirstOrDefault();
            if(user == null) {
                return Json(new { success = false, reason = "The user could not be found." });
            }
            bool isInRole = _userManager.IsInRoleAsync(user, role).Result;
            if (isInRole) {
                if(role.Equals("Admin") && _userManager.GetUsersInRoleAsync("Admin").Result.Count() == 1) {
                    return Json(new { success = false, reason = "This is the last administrator." });
                }
                _userManager.RemoveFromRoleAsync(user, role).Wait();
            } else {
                _userManager.AddToRoleAsync(user, role).Wait();
            }
            return Json(new { success = true, isRole = !isInRole });
        }

        /// <summary>
        /// Removes the specified user. Prevents the current user from deleting themself.
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public JsonResult RemoveUser(string username) {
            IdentityUser user = _userContext.Users.Where(u => u.UserName == username).FirstOrDefault();
            if (user == null || user.UserName == User.Identity.Name) return Json(new { success = false });
            _userManager.DeleteAsync(user).Wait();
            return Json(new { success = true });
        }

    }
}

CS4540PS2/Views/Home/Index.cshtml
@*
    Author: Valerie German
    Date: 18 Oct 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
    I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: This file contains sample homepage for PS4/5.
*@
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">Learning Objective Tracker</h3>
    <hr />
</div>
<table class="button-container" width="100%">
    <col width="25%">
    <col width="25%">
    <col width="25%">
    <col width="25%">
    <tr>
        <th class="lot-th">Admin</th>
    </tr>
    <tr>
        <td>
            <a asp-controller="Course" asp-action="Index" class="btn lot-icon">
                <img src="~/files/images/books_logo.png" /><br />
                <b>All Courses</b>
            </a>
        </td>
        <td>
            <a asp-controller="DeptManager" asp-action="Index" class="btn lot-icon">
                <img src="~/files/images/depts.png" /><br />
                <b>Departments</b>
            </a>            
        </td>
        <td>
            <a asp-controller="LearningOutcomes" asp-action="Index" class="btn lot-icon">
                <img src="~/files/images/brain logo.png" /><br />
                <b>Learning Outcomes</b>
            </a>            
        <td>
            <a asp-controller="User" asp-action="Index" class="btn lot-icon">
                <img src="~/files/images/users.png" /><br />
                <b>User Roles</b>
            </a>           
        </td>
    </tr>
    <tr>
        <th class="lot-th">Chair</th>
    </tr>
    <tr>       
        <td>
            <a asp-controller="Department" asp-action="Department" class="btn lot-icon">
                <img src="~/files/images/dept_overview.png" /><br />
                <b>Department Overview</b>
            </a>
        </td>
        <td>
            <a asp-controller="Home" asp-action="Notifications" class="btn lot-icon">
                <img src="~/files/images/notification.png" /><br />
                <b>Notifications</b>
            </a>            
        </td>
    </tr>  
    <tr>
        <th class="lot-th">Instructor</th>
    </tr>
    <tr>
        <td>
            <a asp-controller="Instructor" asp-action="ArchivedCourses" class="btn lot-icon">
                <img src="~/files/images/archive.png" /><br />
                <b>Archived Courses</b>
            </a>
        </td>
        <td>
            <a asp-controller="Instructor" asp-action="Index" class="btn lot-icon">
                <img src="~/files/images/courses overview.png" /><br />
                <b>Courses Overview</b>
            </a>
        </td>
        <td>
            <a asp-controller="Home" asp-action="Notifications" class="btn lot-icon">
                <img src="~/files/images/notification.png" /><br />
                <b>Notifications</b>
            </a>
        </td>
    </tr>

</table>

CS4540PS2/Views/Home/Notifications.cshtml
@model CS4540PS2.Models.UserLocator
@using Microsoft.AspNetCore.Identity;
@*
    Author: Valerie German
    Date: 3 Dec 2019
    Course: CS 4540, University of Utah
    Copyright: CS 4540 and Valerie German - This work may not be copied for use in Academic Coursework.
    I, Valerie German, certify that I wrote this code from scratch and did not copy it in part or whole from another source. Any references used in the completion of this assignment are cited in my README file.
    File Contents: View for user notifications.
*@
@{
    ViewData["Title"] = "Notifications";
}
<br />
<h3>Notifications</h3>
<hr />
@if (Model.Notifications.Any()) {
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">Date Received</th>
                <th scope="col">Message</th>
                <th scope="col" colspan="2">Course</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Notifications notify in Model.Notifications.OrderByDescending(n => n.DateNotified)) {
                var read = !notify.Read ? "bg-dark text-light" : "bg-light text-dark";
                var rowId = "row" + notify.NotificationId;
                var readId = "readCol" + notify.NotificationId;
                <tr id="@rowId" class="@read">
                    <td>
                        <button class="btn-danger btn-sm" onclick="DeleteNotify(event, @notify.NotificationId, '@rowId')">X</button>
                    </td>
                    <td id="@readId">
                        @if (!notify.Read) {<button class="btn-light btn-sm" onclick="ReadNotify(event, @notify.NotificationId, '@rowId', '@readId')">Mark as Read</button>}
                    </td>
                    <td>@notify.DateNotified.ToString("dddd, dd MMMM yyyy")</td>
                    <td>@notify.Text</td>
                    @{
                        CourseInstance course = notify.CourseInstance;
                        var courseInfo = course.Department + course.Number + " " + course.Name;
                    }
                    <td>@courseInfo</td>
                    <td>
                        @if (User.IsInRole("Chair")) {
                            <a asp-controller="Department" asp-action="Course" asp-route-courseId="@course.CourseInstanceId">
                                <button class="btn-primary btn-sm">Go To Course</button>
                            </a>
                        } else if (User.IsInRole("Instructor")) {
                            <a asp-controller="Instructor" asp-action="Course" asp-route-Dept="@notify.CourseInstance.Department" asp-route-Num="@notify.CourseInstance.Number"
                               asp-route-Sem="@notify.CourseInstance.Semester" asp-route-Year="@notify.CourseInstance.Year"><button class="btn-primary btn-sm">Go To Course</button></a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>You have no notifications.</p>
}